### ISSUE TITLE
ruim 16 errors

### ISSUE THREAD

**Issue by Theo-denBlanken** [25953/modaal#1]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/25953/modaal/blob/master/

Feedback: bij validatie[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by KevinKranenburg** [comment]
errors weggewerkt

**Comment by Theo-denBlanken** [comment]
ik zie nog steeds veel errors in https://validator.w3.org/nu/?doc=http%3A%2F%2F25953.hosts2.ma-cloud.nl%2Fbewijzenmap%2Fperiode1.3%2Ffro%2Fmodaal%2F<https://validator.w3.org/nu/?doc=http://25953.hosts2.ma-cloud.nl/bewijzenmap/periode1.3/fro/modaal/>


met vriendelijke groeten,
-


[ma-logo]
Theo den Blanken
        [Theo] <http://blanken5.home.xs4all.nl/>
docent
Mediadeveloper
Mediacollege Amsterdam  [Twitter] <https://twitter.com/theodenblanken/>  [WordPress] <http://bla.hosts.ma-cloud.nl/>




Op 26 mrt. 2019, om 09:23 heeft Kevin <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Closed #1<https://github.com/25953/modaal/issues/1>.
