### ISSUE TITLE
ondanks de eigen vormgeving

### ISSUE THREAD

**Issue by Theo-denBlanken** [25953/modaal#2]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/25953/modaal/blob/master/

Feedback: ligt de gebruikte class-namen wel erg dicht bij het voorbeeld!![](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by KevinKranenburg** [comment]
class namen aangepast
